In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [1]:
import cv2
import albumentations as A

In [9]:
path = "D:/Documents/GitHub/image_pipeline/data/aerial-cactus-identification/train.csv"
df = pd.read_csv(path)
df.head()

id  has_cactus
0  0004be2cfeaba1c0361d39e2b000257b.jpg           1
1  000c8a36845c0208e833c79c1bffedd1.jpg           1
2  000d1e9a533f62e55c289303b072733d.jpg           1
3  0011485b40695e9138e92d0b3fb55128.jpg           1
4  0014d7a11e90b62848904c1418fc8cf2.jpg           1

In [27]:
y = {"x1" : 3, "x2" : 5, "x3": 6}
len(y)
y["x1"]

3

In [6]:
regression_metrics = ["mae", "mse", "rmse"]
loss = ["loss"]
regression_metrics + loss

['mae', 'mse', 'rmse', 'loss']

In [7]:
regression_metrics + loss

['mae', 'mse', 'rmse', 'loss']

In [2]:
import torch
import torch.nn as nn

In [18]:
x = torch.randn(2,2)
x

tensor([[-1.2762, -1.8564],
        [ 0.9928,  1.0522]])

In [24]:
x.softmax(dim=0)

tensor([[0.0937, 0.0517],
        [0.9063, 0.9483]])

In [22]:
x.softmax(dim=1)[:, 1]

tensor([0.3589, 0.5148])

In [17]:
m = nn.Sigmoid()
m(x)

tensor([[0.2531, 0.5738, 0.7234],
        [0.4391, 0.5894, 0.1146],
        [0.3479, 0.3682, 0.0815]])