In [1]:
import datetime

In [8]:
str(datetime.date.today().isoformat())

'2021-05-22'

In [1]:
string = "projects/AERIAL_CACTUS/model_output/model_RESNET18_2021-05-25_0.bin"

In [19]:
string.rsplit("_", 1)[0]

'model_resnet_0.956'

In [3]:
fold = 2

In [4]:
string.rsplit("_", 1)[0] + "_" + str(fold) + ".bin"

'projects/AERIAL_CACTUS/model_output/model_RESNET18_2021-05-25_2.bin'

In [12]:
import glob
image_path = []
for filename in glob.glob(os.path.join("D:/Documents/GitHub/image_pipeline/data/aerial-cactus-identification/test/", "*.jpg")):
    filename = filename.split("\\", -1)[-1]
    image_path.append(filename)

In [5]:
import pandas as pd
import glob
image_path = []
for filename in glob.glob(os.path.join("D:/Documents/GitHub/image_pipeline/data/aerial-cactus-identification/test/", "*.jpg")):
    filename = filename.split("\\", -1)[-1]
    image_path.append(filename)
df_test = pd.DataFrame({"id" : image_path})

In [7]:
df_test

id
0     000940378805c44108d287872b2f04ce.jpg
1     0017242f54ececa4512b4d7937d1e21e.jpg
2     001ee6d8564003107853118ab87df407.jpg
3     002e175c3c1e060769475f52182583d0.jpg
4     0036e44a7e8f7218e9bc7bf8137e4943.jpg
...                                    ...
3995  ffaafd0c9f2f0e73172848463bc2e523.jpg
3996  ffae37344310a1549162493237d25d3f.jpg
3997  ffbd469c56873d064326204aac546e0d.jpg
3998  ffcb76b7d47f29ece11c751e5f763f52.jpg
3999  fffed17d1a8e0433a934db518d7f532c.jpg

[4000 rows x 1 columns]

In [10]:
import torch
input = torch.randn(2, 2)
input

tensor([[-0.4279,  0.9360],
        [-0.0196, -0.2432]])

In [2]:
input.softmax(dim=0)

tensor([[0.3935, 0.8288],
        [0.6065, 0.1712]])

In [3]:
input.softmax(dim=1)

tensor([[0.5163, 0.4837],
        [0.8885, 0.1115]])

In [11]:
import numpy as np 
input = input.cpu().detach().numpy()
index = input.argmax(axis=1)
max = input[index]

In [12]:
index

array([1, 0], dtype=int64)

In [13]:
max

array([[-0.01956172, -0.24322473],
       [-0.42787918,  0.9360284 ]], dtype=float32)

In [14]:
input

array([[-0.42787918,  0.9360284 ],
       [-0.01956172, -0.24322473]], dtype=float32)